function batchJFCDecode()
%BATCHJFCDECODE Summary of this function goes here

%% define co-parameters
outdir = 'F://IFEFSR//SpeechData//';
infile = 'F://IFEFSR//ExpSphinx//an4traintest_small.txt';
indir = 'F://IFEFSR//AudioFC//FC//TEST//';
inext = 'mat';
outext = 'raw';

%% define experiments parameters set
FS = [{'8'}, {'16'}];
RBS = [{'128'}, {'64'}, {'32'}, {'16'}, {'8'}, {'4'}, {'2'}];
P = buildParamsMatrix( FS, RBS );

for expIdx = 1:length(P)
    fs = P{expIdx, 1};
    rbs = P{expIdx, 2};
    
    %% construct parameter values
    testname = ['RECAN4' fs '_FP_RBS' rbs];
    inpathprefix = [indir 'AN4' fs '_FP_RBS' rbs '//'];
    alpha = '1';
    if strcmp('8', fs)
        alpha = '2';
    end
    
    %% exec JFC
    execJFC( ...
        'processname decompress', ...
        ['testname ' testname], ...
        ['infile ' infile], ...
        ['inpathprefix ' inpathprefix], ...
        ['outdir ' outdir], ...
        'maxprocess 1', ...
        ['inext ' inext], ...
        ['outext ' outext], ...
        ['pthresh 0'], ...
        'reportrate 0', ...
        'skipifexist false', ...
        ['samplingrate ' fs '000'], ...
        ['alpha ' alpha], ...
        ['minr ' rbs], ...
        ['maxr ' rbs] ...
        );
    
end

